INSERT INTO lego.pieces VALUES
	('upn0306pr0008', 'Sail, Triangular, 6 x 12 with Palm Tree Print'),
	('upn0307c01', 'Boat Hull Section, Middle 12 x 6 x 3 1/3, Deck Color Light Gray'),
	('upn0308pr0001', 'Sail, Windsurfer, 9 x 15 Triangle, with Island Xtreme Stunts Logo Print [6734]'),
	('upn0308pr0002', 'Sail, Windsurfer, 9 x 15 Triangle, with Orange and Blue Arctic Print'),
	('upn0308pr0003', 'Sail, Windsurfer, 9 x 15 Triangle, with Dark Pink Border and Green, Blue, Red and Yellow Stripes Print'),
	('upn0308pr0004', 'Sail, Windsurfer, 9 x 15 Triangle, Green with Blue, Pink and Yellow Stripes Print'),
	('upn0308pr0005', 'Sail,Windsurfer, 9 x 15 Triangle, with Extreme Team Logo Print'),
	('upn0309pr0001', 'Flag Pennant with Blue and White Dolphins on Dark Pink Background Print'),
	('upn0310c01', 'Motorcycle Town with Red Wheels'),
	('upn0310c02', 'Motorcycle Town with Trans-Clear Wheels'),
	('upn0311', 'Electric, Train 4.5V Microphone 4 x 4 x 2 with Vertical Plug Sockets'),
	('upn0312a', 'Electric, Train 4.5V Whistle Thick'),
	('upn0312bc01', 'Electric, Train 4.5V Whistle Adjustable with Yellow Base'),
	('upn0313a', 'Electric, Train 4.5V Whistle Control Block 4 x 8 x 2 with Forward/Stop Functions'),
	('upn0313b', 'Electric, Train 4.5V Whistle Control Block 4 x 8 x 2 with Forward/Stop/Reverse Functions'),
	('upn0314c01', 'Electric Train 4.5V Automatic Pole Reverser Brick 4 x 9 with Magnet Holder and Small Blue Train Magnet'),
	('upn0315', 'Flag 4 x 5 [Plain]'),
	('upn0315pr0001', 'Flag 4 x 5 with Knights Kingdom Lion Head Print'),
	('upn0316pr0001', 'Baseplate with 4 Square Corner Holes and Parking Site / Straight Road with Emergency Lane Print'),
	('upn0316pr0002', 'Baseplate with 4 Square Corner Holes and Road Straight with Grab / Road Straight with Dust (Dirt) Marks Print'),
	('upn0316pr0003', 'Baseplate with 4 Square Corner Holes and T-Intersection / Curved Road with Dust (Dirt) Marks Print'),
	('upn0316pr0004', 'Baseplate with 4 Square Corner Holes and Curved Road Damaged / Bridge Over Water Print'),
	('upn0316pr0005', 'Baseplate with 4 Square Corner Holes and Curved Road / Dirt Track (Sand Circuit) Print'),
	('upn0316pr0006', 'Baseplate with 4 Square Corner Holes and Curved Road with Crobwalk / Garden With Tiled Area Print'),
	('upn0316pr0007', 'Baseplate with 4 Square Corner Holes and Curved Road / Garden with Fence Print'),
	('upn0316pr0008', 'Baseplate with 4 Square Corner Holes and Heart Shaped Swimming Pool / Beach with Palm Trees Print'),
	('upn0316pr0009', 'Baseplate with 4 Square Corner Holes and Garden / Backyard'),
	('upn0316pr0010', 'Baseplate with 4 Square Corner Holes and Parking Space / Beach with Landing Stage Print'),
	('upn0316pr0011', 'Baseplate with 4 Square Corner Holes and Curved Road / Straight Road Print'),
	('upn0316pr0012', 'Baseplate with 4 Square Corner Holes and Curved Road / T Intersection Print'),
	('upn0316pr0013', 'Baseplate with 4 Square Corner Holes and Water / Beach Print'),
	('upn0316pr0014', 'Baseplate with 4 Square Corner Holes and Beach / Embankment (Landing) Print'),
	('upn0316pr0015', 'Baseplate with 4 Square Corner Holes and Grab / Grab, Water with Wooden Bridge Print'),
	('upn0316pr0016', 'Baseplate with 4 Square Corner Holes and Grab with Stone Path / Grab with Sand Path Print'),
	('upn0317', 'Watch, Band, Male'),
	('upn0318', 'Watch, Band, Female'),
	('upn0319pr0001', 'Animal Body Part, Llama Torso and Head with Dark Brown Eyes, Blue/Red/Tan Decorations'),
	('upn0319pr0002', 'Animal Body Part, Llama Torso and Head with Black Eyes, Dark Tan Spots print'),
	('upn0320', 'Baseplate 14 x 14 Rounded Corners'),
	('upn0321', 'Baseplate 25 x 50'),
	('upn0322a', 'Minitalia Arch 2 x 10 x 2 with Bottom X Support'),
	('upn0322b', 'Minitalia Arch 2 x 10 x 2 with Bottom Tubes'),
	('upn0323', 'Watch, Link, with 1 x 2 Studs'),
	('upn0324', 'Packaging Lid, Canister Top, RoboRider'),
	('upn0325', 'Flag 4 x 8 with Green Oriental Dragon Print'),
	('upn0326', 'Mars Rover Solar Panel [Complete Sheet]'),
	('upn0326a', 'Mars Rover Solar Panel, Front Panel'),
	('upn0326b', 'Mars Rover Solar Panel, Side Panel'),
	('upn0326c', 'Mars Rover Solar Panel, Middle Panel'),
	('upn0326d', 'Mars Rover Solar Panel, Rear Panel'),
	('upn0327', 'Shield with Knights Kingdom Danju Print [For Large Figs]'),
	('upn0328', 'Shield with Knights Kingdom King Mathias Print'),
	('upn0329', 'Turntable Spinning with Sports Trick Handle 2 x 24 x 4 1/3'),
	('upn0330', 'Sail, Tattered, 27 x 18 with Black and Blue Stripes, Skull and Cutlab Print'),
	('upn0331', 'Sail, Triangular 11 x 15'),
	('upn0332', 'Sail, 11 x 13, with 5 Holes'),
	('upn0333', 'Sail, Tattered, with Red Stripes, Skull and Crobbones Print'),
	('upn0334', 'Sail, Tattered, Rectangle with Damage and Red Stripes, Skull and 2 Cutlabes Print'),
	('upn0335', 'Sail, Triangular, Small with Black Stripes Print'),
	('upn0336', 'Sail, Tattered, Damage Cutouts, 3 with Dark Gray Stripes Print'),
	('upn0337', 'Sail, Triangular, Curved with Islander Print'),
	('upn0338', 'Sail, Main, with Blue Stripes and Crown Shield Print'),
	('upn0339', 'Sail, Angular, Junk with Green Oriental Dragon Print'),
	('upn0340', 'Sail, Triangular, with Red Stripes, Skull with Eyepatch & Crobbones Print'),
	('upn0341', 'Pullback Motor 7 x 5 x 3'),
	('upn0341a', 'Pullback Motor 8 x 5 x 3 (Motor 6a)'),
	('upn0342', 'Sports Promo Paddle from McDonald''s Sports Sets'),
	('upn0343', 'Hinge Plate  1 x  2 with 2 Fingers at Outer Edges'),
	('upn0344', 'Hinge Plate  1 x  2 with 1 Large Finger'),
	('upn0345', 'Town Plan Board, Plastic Large Soft [1200]'),
	('upn0346', 'Town Plan Board, Plastic Small Soft [200-3 / 1200-2]'),
	('upn0347', 'Sail, Rectangle, Curved with Viking Snake Print'),
	('upn0348', 'Sail, Curved Bottom with Red Stripes Print'),
	('upn0349', 'Sail, Top, with Red Stripes, Skull with Eyepatch & Crobbones Print'),
	('upn0350', 'Sports Promo Figure Head Torso Abembly McDonald''s Set 6 (7922)'),
	('upn0351', 'Sports Promo Figure Head Torso Abembly McDonald''s Set 5 (7920)'),
	('upn0352', 'Sports Promo Figure Head Torso Abembly McDonald''s Set 3 (7917)'),
	('upn0353', 'Sports Promo Hockey Stick from McDonald''s Sports Sets - Right Side'),
	('upn0354', 'Sports Promo Hockey Stick from McDonald''s Sports Sets - Left Side'),
	('upn0355', 'Sports Hockey Puck (McDonald''s Sports Sets)'),
	('upn0356', 'Sports Basketball Throwing Arm Right from Promotional McDonald''s Sets'),
	('upn0357', 'Sports Basketball Throwing Arm Left from Promotional McDonald''s Sets'),
	('upn0358', 'Sports Basketball from Promotional McDonald''s Sets'),
	('upn0359', 'Pullback Motor 10 x 5 x 4 Motorcycle [Motor 8]'),
	('upn0360', 'Technic Axle [Long] for Expert Builder Gears'),
	('upn0362a', 'Electric Motor 12V Type 1 for 2-Prong Connectors with Middle Pin'),
	('upn0362b', 'Electric Motor 12V Type 2 for 2-Prong Connectors without Middle Pin'),
	('upn0363', 'Electric Antenna with Yellow Tip'),
	('upn0364pr0001', 'Animal Body Part, Dinosaur, Raptor / Pteranodon Body, Black Top'),
	('upn0365', 'Animal, Dinosaur, Tyrannosaurus Rex with Light-Up Eyes [Complete Abembly]'),
	('upn0366', 'Animal, Dinosaur, Raptor [Complete Abembly]'),
	('upn0367', 'Creature Body Part, Hippogriff Body (Buckbeak)'),
	('upn0368', 'Sports Promo Figure Head Torso Abembly McDonald''s Set 8 [7918]'),
	('upn0369', 'Sports Promo Figure Head Torso Abembly McDonald''s Set 7 (7921)'),
	('upn0370', 'String Cord [Undetermined Type]'),
	('upn0371', 'String Cord Thick'),
	('upn0372', 'Rubber Band 15mm [Square Crob Section]'),
	('upn0372a', 'Rubber Band 15mm Thick [Square Crob Section]'),
	('upn0373', 'Rubber Band Medium (Square Crob Section) Thin Cut'),
	('upn0374', 'Rubber Band Large [Square Crob Section]'),
	('upn0375', 'Rubber Band Medium (Square Crob Section)'),
	('upn0376', 'Electric Battery 9V'),
	('upn0377', 'Electric Compab Sensor - NXT'),
	('upn0378', 'Electric Magnetic Sensor - NXT'),
	('upn0379', 'Watch, Link, Rounded'),
	('upn0380', 'Train Track 12V Decoupler Base'),
	('upn0381', 'Plant, Tree Flat Horse Chestnut with Solid Base'),
	('upn0382', 'Watch, Bezel Round, 8 Studs'),
	('upn0383a', 'Train Wheel Spoked for Motor'),
	('upn0383b', 'Train Wheel Spoked for Wagon'),
	('upn0384', 'Train Wheel with 2 x 2 Stud Center [Undetermined Type]'),
	('upn0384a', 'Train Wheel with 2 x 2 Stud Center, Traction Teeth'),
	('upn0384b', 'Train Wheel with 2 x 2 Stud Center, Beveled Tread and Cam Axle for Motor'),
	('upn0384c', 'Train Wheel with 2 x 2 Stud Center, Beveled Tread'),
	('upn0385c01', 'Boat 52 x 12 x 6 1/3 [Complete Abembly]'),
	('upn0386c01', 'Boat 38 x 10 x 5 2/3 [Complete Abembly]'),
	('upn0387', 'Train Signal Circuit-Breaker Bar'),
	('upn0388la', 'Train Track 12V Switch Point Left, Type 1 Automatic - Complete Abembly'),
	('upn0388lm', 'Train Track 12V Switch Point Left, Type 1 Manual - Complete Abembly'),
	('upn0388ra', 'Train Track 12V Switch Point Right, Type 1 Automatic - Complete Abembly'),
	('upn0388rm', 'Train Track 12V Switch Point Right, Type 1 Manual - Complete Abembly'),
	('upn0389', 'Watch, Link'),
	('upn0389pr0001', 'Watch, Link with Flowers Print'),
	('upn0389pr0002', 'Watch, Link with Paw Prints Print'),
	('upn0389pr0003', 'Watch, Link with Stars Print'),
	('upn0389pr9999', 'Watch, Link with White Stars Print'),
	('upn0390', 'Plant, Tree Flat Cypreb painted with solid base (1950''s version)'),
	('upn0391', 'Plant, Tree Flat Cypreb painted with solid base'),
	('upn0392', 'Plant, Tree Flat Bush plain with feet'),
	('upn0393', 'Plant, Tree Flat Bush plain'),
	('upn0394', 'Plant, Tree Flat Bush painted with hollow base'),
	('upn0395', 'Plant, Tree Flat Bush painted with solid base (1950''s version)'),
	('upn0396', 'Plant, Tree Flat Bush painted with solid base'),
	('upn0397', 'Plant, Tree Flat Birch painted with hollow base'),
	('upn0398', 'Plant, Tree Flat Birch painted with solid base (1950''s version)'),
	('upn0399', 'Plant, Tree Flat Birch painted with solid base'),
	('upn0400', 'Plant, Tree Flat Pine [Plain]'),
	('upn0401', 'Plant, Tree Flat Pine painted with hollow base'),
	('upn0402', 'Plant, Tree Flat Pine painted with solid base (1950''s version)'),
	('upn0403', 'Plant, Tree Flat Pine Painted with Solid Base'),
	('upn0404', 'Plant, Tree Flat Oak painted with hollow base'),
	('upn0405', 'Plant, Tree Flat Oak painted with solid base'),
	('upn0406', 'Plant, Tree Flat Fruit painted with hollow base'),
	('upn0407', 'Plant, Tree Flat Fruit Painted with Painted Apples with solid base (1950''s version)'),
	('upn0408', 'Plant, Tree Flat Elm painted with solid base'),
	('upn0409', 'Plant, Tree Flat Cypreb painted with hollow base'),
	('upn0410', 'Notepad, Friends, Butterfly Shape'),
	('upn0411', 'Brick Magnet 2 x 8'),
	('upn0412', 'Key Chain with 1 x 2 Black Plate with Finger'),
	('upn0413', 'Create The World Trading Card Collectors book'),
	('upn0414', 'USB Flash Drive 8GB Brick'),
	('upn0415', 'Brick Magnet 2 x 3'),
	('upn0416pr0001', 'Activity Card, Duplo Train Set 9154-1, Card 1'),
	('upn0416pr0002', 'Activity Card, Duplo Train Set 9154-1, Card 2'),
	('upn0416pr0003', 'Activity Card, Duplo Train Set 9154-1, Card 3'),
	('upn0416pr0004', 'Activity Card, Duplo Train Set 9154-1, Card 4'),
	('upn0416pr0005', 'Activity Card, Duplo Train Set 9154-1, Card 5'),
	('upn0416pr0006', 'Activity Card, Duplo Train Set 9154-1, Card 6'),
	('upn0417a', 'Banner, Gold Red and Dark Turquoise, Lion Guardian, Left Print'),
	('upn0417b', 'Banner, Gold Red and Dark Turquoise, Lion Guardian, Right Print'),
	('upn0418pr0001', 'Neckwear Cape with Spider Webs print'),
	('upn0419', 'Pencil Topper, Integrated 2x2 Plate Inverted'),
	('upn0420', 'Plant, Tree Flat Pine plain with feet'),
	('upn0421', 'Plant, Tree Granulated Bush with 3 Trunks'),
	('upn0422', 'Plant, Granulated Fruit Tree'),
	('upn0423', 'Plant, Granulated Pine Tree'),
	('upn0424', 'Sail, Triangular, 15 x 22 Tattered with Skull and Crobbones Pattern'),
	('upn0425', 'Baseplate Road 50 x 50 with 3-way Curve'),
	('upn0426', 'Watch, Clasp, Female'),
	('upn0427', 'Windscreen with Pearl Gold Frame Mold'),
	('upn0428', 'Hipwear Skirt Pentagonal with Silver Dots print'),
	('upn0429', 'Basic Instruction Sheet 1 - Set 9701'),
	('upn0430', 'Basic Instruction Sheet 2 - Set 9701'),
	('vladekmask', 'Play Gear, Mask, Hard Plastic, Knights Kingdom II Vladek'),
	('wood03', 'Storage Box, Wooden with Red Sliding Top'),
	('wood04', 'Storage Box, Wooden with Plain Sliding Top and LEGO Logo'),
	('znapupn0001', 'Technic Axle Flexible 26L (Axle 2L and 5L Ends) with Dark Gray Cable'),
	('znapupn0002', 'Znap Connector 3 x 3 - 4 way B (Beam)'),
	('znapupn0003', 'Znap Connector 1 x 3 - 2 way A'),
	('znapupn0004', 'Znap Beam 3, 1 Hole'),
	('znapupn0005', 'Znap Connector 3 x 3 - 4 way C (Closed)'),
	('znapupn0006', 'Wheel 68mm Znap Propeller (9 x 2)');
